export const priorityOptions = [
  { value: "5", label: "Top priority" },
  { value: "4", label: "High priority" },
  { value: "3", label: "Medium priority" },
  { value: "2", label: "Low priority" },
  { value: "1", label: "Lowest priority" },
];

export const difficultyOptions = [
  { value: "5", label: "Very challenging" },
  { value: "4", label: "Challenging" },
  { value: "3", label: "Moderate" },
  { value: "2", label: "Easy" },
  { value: "1", label: "Very easy" },
];

export const genderOptions = [
  "Select employee gender",
  "male",
  "female",
  "I will rather not say",
];

export const visaOptions = [
  "Select visa type",
  "F2A - Non-Accredited Diplomatic Visa",
  "F3B - Transit Without Visa",
  "F3C - Transit With Visa",
  "F4A - Business - Single Entry Visa",
  "F4B - Business - Multiple Entry Visa",
  "F4C - Business - Frequently Traveled Executives Visa",
  "F5A - Tourism Visa",
  "F6A - Visiting Visa",
  "F6B - Visiting Visa",
  "F7A - Journalist Visa",
  "F7B - Cleric Visa",
  "F7C - Medical Tourism Visa",
  "F7D - Religious Tourism Visa",
  "F7E - Sport Visa",
  "F7F - Entertainer Visa",
  "F7G - Study Tour Visa",
  "F7H - Academic Exchange Program (AEP) Visa",
  "F7I - International Culture Exchange Visa",
  "F7J - Humanitarian Service Visa",
  "F7K - Emergency/Relief Work Visa",
  "F7L - Staff of International NGO Visa",
  "F7M - Staff of NGO Visa",
  "F8A - Temporary Work Permit Visa",
  "F9A - Returning Nigerian by Birth Visa",
  "R11 - Temporary Work Permit Visa",
  "R1A - Accredited Diplomatic Visa",
  "R1B - Spouse of Accredited Diplomatic Visa",
  "R1C - Minor Dependant of Accredited Diplomatic Visa",
  "R1D - Adult Dependant of Accredited Diplomatic Visa",
  "R1E - Aged Dependant of Accredited Diplomatic Visa",
  "R2A - Expatriate Employment Visa",
  "R2B - Spouse of Expatriate Visa",
  "R2C - Minor Dependant of Expatriate Visa",
  "R2D - Adult Dependant of Expatriate Visa",
  "R2E - Aged Dependant of Expatriate Visa",
  "R3A - Free Zone Expatriate Employment Visa",
  "R3B - Spouse of Free Zone Expatriate Visa",
  "R3C - Minor Dependant of Free Zone Expatriate Visa",
  "R3D - Adult Dependant of Free Zone Expatriate Visa",
  "R3E - Aged Dependant of Free Zone Expatriate Visa",
  "R4A - Government Expatriate Employment Visa",
  "R4B - Spouse of Government Expatriate Visa",
  "R4C - Minor Dependant of Government Expatriate Visa",
  "R4D - Adult Dependant of Government Expatriate Visa",
  "R4E - Aged Dependant of Government Expatriate Visa",
  "R5A - International NGO Employment Visa",
  "R5B - Spouse of INGO Employment Visa",
  "R5C - Minor Dependant of INGO Employment Visa",
  "R5D - Adult Dependant of INGO Employment Visa",
  "R5E - Aged Dependant of INGO Employment Visa",
  "R6A - Cleric Employment Visa",
  "R6B - Spouse of Cleric Employment Visa",
  "R6C - Minor Dependant of Cleric Employment Visa",
  "R6D - Adult Dependant of Cleric Employment Visa",
  "R6E - Aged Dependant of Cleric Employment Visa",
  "R7A - Student Visa",
  "R7B - Spouse of Student Visa",
  "R8A - Academic Exchange Programme (AEP) Visa",
  "R8B - Spouse of AEP Visa",
  "R9A - Intern Visa",
  "N1A - Spouse of Nigerian Citizen Visa",
  "N2A - Nigerian by Birth who Renounced Nigerian Citizenship Visa",
  "N2B - Spouse of Nigerian by Birth who Renounced Nigerian Citizenship Visa",
  "N3A - Small Scale Enterprise Investor Visa",
  "N3B - Medium Scale Enterprise Investor Visa",
  "N3C - Large Scale Corporation Investor Visa",
  "N3D - Ultra Large Scale Corporation Investor Visa",
  "N3E - Oil, Gas and Power Sector Investor Visa",
  "N4A - Highly Skilled Immigrant Visa",
  "N5A - Retiree in Nigeria Visa",
  "N5B - Retiree From Abroad Visa",
  "N6A - Spouse of Permanent Residence Visa",
  "N6B - Minor Dependant of Permanent Residence Visa",
  "N6C - Adult Dependant of Permanent Residence Visa",
  "N6D - Aged Dependant of Permanent Residence Visa",
];

export const disabilityOptions = [
  "Does employee have any disability?",
  "Yes",
  "No",
];
export const isExpatriateOptions = ["Is employee an expatriate?", "Yes", "No"];
export const martialStatusOptions = [
  "Select marital status",
  "single",
  "married",
  "divorced",
  "separated",
  "widowed",
  "other",
  "I will rather not say",
];

export const ACADEMIC_QUALIFICATIONS = [
  "Select qualification",
  "Doctorate",
  "Master's",
  "Post Graduate Diploma",
  "Bachelor's",
  "HND",
  "OND",
  "O Level",
  "A Level",
  "FSLC",
];

export const categoryOptions = [
  "Select staff category",
  "Master",
  "Senior",
  "Junior",
];
export const workLocationOptions = [
  "Do you have any work location objection?",
  "Yes",
  "No",
];
export const typeOfEmploymentOptions = [
  "Enter type of employment",
  "full time",
  "full time remote",
  "part time",
  "part time remote",
  "contract",
  "contract remote",
  "casual worker",
];
