export const projectdata = [

	{
		"buttonText": "A&A Towers",
		"button": "iDotsRounded1",
		'text': "Eko Atlantic City",
		'percent': "pro-percent",
		'percentNumber': "20",
		'percent-progress': "pro-percent",
		'percent-people': "pro-people",
	},
	{
		"buttonText": "Phoenix Rising",
		"button": "iDotsRounded5",
		'text': "Eko Atlantic City",
		'percent': "pro-percent",
		'percentNumber': "70",
		'percent-progress': "pro-percent",
		'percent-people': "pro-people",
	},
	{
		"buttonText": "A&A Towers",
		"button": "iDotsRounded4",
		'text': "Eko Atlantic City",
		'percent': "pro-percent",
		'percentNumber': "30",
		'percent-progress': "pro-percent",
		'percent-people': "pro-people",
	},
	{
		"buttonText": "54 Glover Towers",
		"button": "iDotsRounded3",
		'text': "Ikoyi",
		'percent': "pro-percent",
		'percentNumber': "60",
		'percent-progress': "pro-percent",
		'percent-people': "pro-people",
	},
	{
		"buttonText": "Phoenix Tower",
		"button": "iDotsRounded2",
		'text': "Eko Atlantic City",
		'percent': "pro-percent",
		'percentNumber': "70",
		'percent-progress': "pro-percent",
		'percent-people': "pro-people",
	},
	{
		"buttonText": "54 Glover Towers",
		"button": "iDotsRounded1",
		'text': "Ikoyi",
		'percent': "pro-percent",
		'percentNumber': "10",
		'percent-progress': "pro-percent",
		'percent-people': "pro-people",
	},
	{
		"buttonText": "Bijou",
		"button": "iDotsRounded5",
		'text': "Banana Island",
		'percent': "pro-percent",
		'percentNumber': "90",
		'percent-progress': "pro-percent",
		'percent-people': "pro-people",
	},
	{
		"buttonText": "Lapaz Apartments",
		"button": "iDotsRounded4",
		'text': "Victoria Island",
		'percent': "pro-percent",
		'percentNumber': "20",
		'percent-progress': "pro-percent",
		'percent-people': "pro-people",
	},
	{
		"buttonText": "Hive",
		"button": "iDotsRounded3",
		'text': "Eko Atlantic City",
		'percent': "pro-percent",
		'percentNumber': "50",
		'percent-progress': "pro-percent",
		'percent-people': "pro-people",
	},
	{
		"buttonText": "Inventory",
		"button": "iDotsRounded2",
		'text': "wireframming, morkup, client, collaboration",
		'percent': "pro-percent",
		'percentNumber': "80",
		'percent-progress': "pro-percent",
		'percent-people': "pro-people",
	},
	{
		"buttonText": "Job",
		"button": "iDotsRounded1",
		'text': "wireframming, morkup, client, collaboration",
		'percent': "pro-percent",
		'percentNumber': "50",
		'percent-progress': "pro-percent",
		'percent-people': "pro-people",
	},
	{
		"buttonText": "A&A Towers",
		"button": "iDotsRounded5",
		'text': "Eko Atlantic City",
		'percent': "pro-percent",
		'percentNumber': "40",
		'percent-progress': "pro-percent",
		'percent-people': "pro-people",
	},
	{
		"buttonText": "A&A Towers",
		"button": "iDotsRounded4",
		'text': "Eko Atlantic City",
		'percent': "pro-percent",
		'percentNumber': "70",
		'percent-progress': "pro-percent",
		'percent-people': "pro-people",
	},
	{
		"buttonText": "Video",
		"button": "iDotsRounded3",
		'text': "wireframming, morkup, client, collaboration",
		'percent': "pro-percent",
		'percentNumber': "50",
		'percent-progress': "pro-percent",
		'percent-people': "pro-people",
	},
	{
		"buttonText": "Money",
		"button": "iDotsRounded2",
		'text': "wireframming, morkup, client, collaboration",
		'percent': "pro-percent",
		'percentNumber': "80",
		'percent-progress': "pro-percent",
		'percent-people': "pro-people",
	},

]